module: UserActions
author: Matt Moriarity
author_url: https://www.mattmoriarity.com/
github_url: https://github.com/mjm/UserActions

build_tool_arguments:
  - "-scheme"
  - "UserActions"
  - "-destination"
  - "generic/platform=iOS"
swift_build_tool: xcodebuild
swift_version: "5.1.2"

theme: fullwidth

abstract: Documentation/Sections/*.md

custom_categories:
  - name: Defining Actions
    children:
      - UserAction
      - SimpleUserAction
      - SyncUserAction
      - ReactiveUserAction
      - DestructiveUserAction

  - name: Performing Actions
    children:
      - UserActions
      - UserActionPresenter
      - UserActionRunnerDelegate
      - UserActionError

  - name: Using Actions in UI
    children:
      - BoundUserAction
      - BoundUserActionOptions
      - UICommand
